ingress:
  annotations:
    kubernetes.io/ingress.class: nginx-public
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: ucp.unblock-analysis.com
      paths:
        - /
    - host: ucp.chainsight.com
      paths:
        - /
  tls:
    - secretName: unblock-ui-tls
      hosts:
        - ucp.unblock-analysis.com
    - secretName: unblock-ui-tls
      hosts:
        - ucp.chainsight.com
            

