stages:
  - validate
  - build
  - test
  - deploy
  - rollout
image: docker:git
variables:
  IMAGE_NAME: unblock-ui
build-dev:
  stage: build
  image: node:10.16.0-stretch
  only:
    refs:
      - /^\d+\.\d+\.\d+-beta$/@unblock/unblock-ui
  before_script:
    - cp $NPM_RC ~/.npmrc
  script:
  - npm install
  - npm run build:dev
  artifacts:
    paths:
    - dist/
build-staging:
  stage: build
  image: node:10.16.0-stretch
  only:
    refs:
      - /^\d+\.\d+\.\d+-ga$/@unblock/unblock-ui
  before_script:
    - cp $NPM_RC ~/.npmrc
  script:
  - npm install
  - npm run build:staging
  artifacts:
    paths:
    - dist/
build-prod:
  stage: build
  image: node:10.16.0-stretch
  only:
    refs:
      - /^\d+\.\d+\.\d+$/@unblock/unblock-ui
  before_script:
    - cp $NPM_RC ~/.npmrc
  script:
  - npm install
  - npm run build:prod
  artifacts:
    paths:
    - dist/
deploy-devel:
  stage: deploy
  image: profyu/gcloud-sdk:218.0.0
  only:
    refs:
    - /^\d+\.\d+\.\d+-beta$/
  dependencies:
  - build-dev
  before_script:
  - export PATH=/google-cloud-sdk/bin/:$PATH
  - gcloud auth activate-service-account --key-file $PROFYU_GCLOUD_SERVICE_KEY
  - gcloud auth configure-docker
  script:
  - docker build . -t $GCR_HOST/$GCLOUD_PROJECT_ID/$IMAGE_NAME:$CI_COMMIT_TAG
  - docker push $GCR_HOST/$GCLOUD_PROJECT_ID/$IMAGE_NAME:$CI_COMMIT_TAG
deploy-staging:
  stage: deploy
  image: profyu/gcloud-sdk:218.0.0
  only:
    refs:
    - /^\d+\.\d+\.\d+-ga$/
  dependencies:
  - build-staging
  before_script:
  - export PATH=/google-cloud-sdk/bin/:$PATH
  - gcloud auth activate-service-account --key-file $GCLOUD_SERVICE_KEY
  - gcloud auth configure-docker
  script:
  - docker build . -t $GCR_HOST/$GCLOUD_PROJECT_ID/$IMAGE_NAME:$CI_COMMIT_TAG
  - docker push $GCR_HOST/$GCLOUD_PROJECT_ID/$IMAGE_NAME:$CI_COMMIT_TAG
deploy-prod:
  stage: deploy
  image: google/cloud-sdk:252.0.0
  only:
    refs:
    - /^\d+\.\d+\.\d+$/
  dependencies:
  - build-prod
  before_script:
  - export PATH=/google-cloud-sdk/bin/:$PATH
  - gcloud auth activate-service-account --key-file $GCLOUD_SERVICE_KEY
  - gcloud auth configure-docker
  script:
  - docker build . -t $GCR_HOST/$GCLOUD_PROJECT_ID/$IMAGE_NAME:$CI_COMMIT_TAG
  - docker push $GCR_HOST/$GCLOUD_PROJECT_ID/$IMAGE_NAME:$CI_COMMIT_TAG
rollout-devel:
  stage: rollout
  image: profyu/kubectl:1.13.0
  variables:
    KUBE_DEPLOY_NS: unblock-devel
    KUBE_DEPLOY_APP: unblock-ui-devel
    KUBE_DEPLOY_CONTAINER: unblock-ui
  only:
    refs:
    - /^\d+\.\d+\.\d+-beta$/
  script:
  - kubectl --server=$DEV_KUBE_URL --token=$DEV_KUBE_TOKEN --insecure-skip-tls-verify=true -n $KUBE_DEPLOY_NS set image deployment.v1.apps/$KUBE_DEPLOY_APP $KUBE_DEPLOY_CONTAINER=$GCR_HOST/$GCLOUD_PROJECT_ID/$IMAGE_NAME:$CI_COMMIT_TAG --record
rollout-staging:
  stage: rollout
  image: profyu/gcloud-sdk:218.0.0
  variables:
    KUBE_DEPLOY_NS: unblock-staging
    KUBE_DEPLOY_APP: unblock-ui-staging
    KUBE_DEPLOY_CONTAINER: unblock-ui
  only:
    refs:
    - /^\d+\.\d+\.\d+-ga$/
  before_script:
  - export PATH=/google-cloud-sdk/bin/:$PATH
  - gcloud auth activate-service-account --key-file $GCLOUD_SERVICE_KEY
  - gcloud container clusters get-credentials $GCLOUD_KUBE_CLUSTER_NAME -z $GCLOUD_KUBE_ZONE --project $GCLOUD_PROJECT_ID
  script:
  - kubectl -n $KUBE_DEPLOY_NS set image deployment.v1.apps/$KUBE_DEPLOY_APP $KUBE_DEPLOY_CONTAINER=$GCR_HOST/$GCLOUD_PROJECT_ID/$IMAGE_NAME:$CI_COMMIT_TAG --record
rollout-prod:
  stage: rollout
  image: profyu/gcloud-sdk:218.0.0
  variables:
    KUBE_DEPLOY_NS: unblock-prod
    KUBE_DEPLOY_APP: unblock-ui-prod
    KUBE_DEPLOY_CONTAINER: unblock-ui
  only:
    refs:
    - /^\d+\.\d+\.\d+$/
  before_script:
  - export PATH=/google-cloud-sdk/bin/:$PATH
  - gcloud auth activate-service-account --key-file $GCLOUD_SERVICE_KEY
  - gcloud container clusters get-credentials $GCLOUD_KUBE_CLUSTER_NAME -z $GCLOUD_KUBE_ZONE --project $GCLOUD_PROJECT_ID
  script:
  - kubectl -n $KUBE_DEPLOY_NS set image deployment.v1.apps/$KUBE_DEPLOY_APP $KUBE_DEPLOY_CONTAINER=$GCR_HOST/$GCLOUD_PROJECT_ID/$IMAGE_NAME:$CI_COMMIT_TAG --record



