/**
 * UnBlock RESTful Web API
 * An Bitcoin analysis service
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface UnBlockApiException {
    apiErrorCode?: UnBlockApiException.ApiErrorCodeEnum;

    cause?: models.Throwable;

    localizedMessage?: string;

    message?: string;

    stackTrace?: Array<models.StackTraceElement>;

    suppressed?: Array<models.Throwable>;

}
export namespace UnBlockApiException {
    export enum ApiErrorCodeEnum {
        ACCOUNTNOTFOUND = <any> 'ACCOUNT_NOT_FOUND',
        UPDATEPASSWORDFALURE = <any> 'UPDATE_PASSWORD_FALURE',
        ROLENOTFOUND = <any> 'ROLE_NOT_FOUND',
        ACCOUNTDISABLED = <any> 'ACCOUNT_DISABLED',
        ACCOUNTLOCKED = <any> 'ACCOUNT_LOCKED',
        BADCREDENTIAL = <any> 'BAD_CREDENTIAL',
        INVALIDREFRESHTOKEN = <any> 'INVALID_REFRESH_TOKEN',
        INVALIDAUTHORIZATIONCODE = <any> 'INVALID_AUTHORIZATION_CODE',
        ACCOUNTEXISTED = <any> 'ACCOUNT_EXISTED',
        DUPLICATEDUSERREGISTRATION = <any> 'DUPLICATED_USER_REGISTRATION',
        ADDRESSNOTFOUND = <any> 'ADDRESS_NOT_FOUND',
        BLOCKNOTFOUND = <any> 'BLOCK_NOT_FOUND',
        TXNOTFOUND = <any> 'TX_NOT_FOUND',
        VOUTNOTFOUND = <any> 'VOUT_NOT_FOUND',
        INVALIDSCRIPT = <any> 'INVALID_SCRIPT',
        SEARCHNOTFOUND = <any> 'SEARCH_NOT_FOUND'
    }
}
