/**
 * UnBlock RESTful Web API
 * An blockchain analysis service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Account { 
    createdTime?: Date;
    email?: string;
    enabled?: boolean;
    firstName?: string;
    googleId?: string;
    id?: number;
    lastName?: string;
    mobile?: string;
    mobileCountryCode?: number;
    otp?: string;
    password?: string;
    principalName?: string;
    unverifiedMobile?: string;
    unverifiedMobileCountryCode?: number;
}

