/**
 * UnBlock RESTful Web API
 * An blockchain analysis service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';
import { BtcFlowRiskJob } from './btc-flow-risk-job';
import { BtcFlowJob } from './btc-flow-job';
import { BtcRiskSummaryJob } from './btc-risk-summary-job';
import { BtcFlowAddressTagJob } from './btc-flow-address-tag-job';
import { BtcFlowAddressTaintJob } from './btc-flow-address-taint-job';


export interface BtcAddressScanPipeline { 
    address?: string;
    avgScore?: number;
    avgScoreEv?: number;
    backwardFlowJob?: BtcFlowJob;
    backwardFlowJobId?: number;
    createdTime?: Date;
    creatorId?: number;
    endingTime?: Date;
    flowAddressTagJob?: BtcFlowAddressTagJob;
    flowAddressTagJobId?: number;
    flowAddressTaintJob?: BtcFlowAddressTaintJob;
    flowAddressTaintJobId?: number;
    flowRiskJob?: BtcFlowRiskJob;
    flowRiskJobId?: number;
    forwardFlowJob?: BtcFlowJob;
    forwardFlowJobId?: number;
    id?: number;
    isCached?: boolean;
    maxLevel?: number;
    riskSummaryJob?: BtcRiskSummaryJob;
    riskSummaryJobId?: number;
    startingTime?: Date;
    status?: BtcAddressScanPipeline.StatusEnum;
    timeoutSecs?: number;
    totalScore?: number;
    totalScoreEv?: number;
    updatedTime?: Date;
    updater?: Account;
}
export namespace BtcAddressScanPipeline {
    export type StatusEnum = 'PENDING' | 'RUNNING' | 'COMPLETED' | 'FAILED';
    export const StatusEnum = {
        PENDING: 'PENDING' as StatusEnum,
        RUNNING: 'RUNNING' as StatusEnum,
        COMPLETED: 'COMPLETED' as StatusEnum,
        FAILED: 'FAILED' as StatusEnum
    };
}


