/**
 * UnBlock RESTful Web API
 * An blockchain analysis service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BtcFlowRiskNodeJob } from './btc-flow-risk-node-job';
import { BtcFlowRiskNodeRecord } from './btc-flow-risk-node-record';
import { BtcFlowRiskEdgeJob } from './btc-flow-risk-edge-job';
import { BtcFlowRiskGraphJob } from './btc-flow-risk-graph-job';
import { BtcFlowRiskEdgeRecord } from './btc-flow-risk-edge-record';


export interface BtcFlowRiskGraph { 
    edges?: Array<BtcFlowRiskEdgeRecord>;
    flowRiskEdgeJob?: BtcFlowRiskEdgeJob;
    flowRiskGraphJob?: BtcFlowRiskGraphJob;
    flowRiskNodeJob?: BtcFlowRiskNodeJob;
    nodes?: Array<BtcFlowRiskNodeRecord>;
}

