/**
 * UnBlock RESTful Web API
 * An blockchain analysis service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EthFlowJob } from './eth-flow-job';


export interface EthFlowJobStatus { 
    done?: boolean;
    job?: EthFlowJob;
}

