/**
 * UnBlock RESTful Web API
 * An blockchain analysis service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';
import { EthFlowAddressTaintJob } from './eth-flow-address-taint-job';
import { EthFlowAddressTagJob } from './eth-flow-address-tag-job';
import { EthFlowRiskJob } from './eth-flow-risk-job';
import { EthRiskSummaryJob } from './eth-risk-summary-job';
import { EthFlowJob } from './eth-flow-job';


export interface EthAddressScanPipeline { 
    address?: string;
    avgScore?: number;
    avgScoreEv?: number;
    backwardFlowJob?: EthFlowJob;
    backwardFlowJobId?: number;
    createdTime?: Date;
    creatorId?: number;
    endingTime?: Date;
    flowAddressTagJob?: EthFlowAddressTagJob;
    flowAddressTagJobId?: number;
    flowAddressTaintJob?: EthFlowAddressTaintJob;
    flowAddressTaintJobId?: number;
    flowRiskJob?: EthFlowRiskJob;
    flowRiskJobId?: number;
    forwardFlowJob?: EthFlowJob;
    forwardFlowJobId?: number;
    id?: number;
    isCached?: boolean;
    maxLevel?: number;
    riskSummaryJob?: EthRiskSummaryJob;
    riskSummaryJobId?: number;
    startingTime?: Date;
    status?: EthAddressScanPipeline.StatusEnum;
    timeoutSecs?: number;
    totalScore?: number;
    totalScoreEv?: number;
    updatedTime?: Date;
    updater?: Account;
}
export namespace EthAddressScanPipeline {
    export type StatusEnum = 'PENDING' | 'RUNNING' | 'COMPLETED' | 'FAILED';
    export const StatusEnum = {
        PENDING: 'PENDING' as StatusEnum,
        RUNNING: 'RUNNING' as StatusEnum,
        COMPLETED: 'COMPLETED' as StatusEnum,
        FAILED: 'FAILED' as StatusEnum
    };
}


