/**
 * UnBlock RESTful Web API
 * An blockchain analysis service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EthFlowRiskEdgeJob } from './eth-flow-risk-edge-job';
import { EthFlowRiskGraphJob } from './eth-flow-risk-graph-job';
import { EthFlowRiskNodeRecord } from './eth-flow-risk-node-record';
import { EthFlowRiskNodeJob } from './eth-flow-risk-node-job';
import { EthFlowRiskEdgeRecord } from './eth-flow-risk-edge-record';


export interface EthFlowRiskGraph { 
    edges?: Array<EthFlowRiskEdgeRecord>;
    flowRiskEdgeJob?: EthFlowRiskEdgeJob;
    flowRiskGraphJob?: EthFlowRiskGraphJob;
    flowRiskNodeJob?: EthFlowRiskNodeJob;
    nodes?: Array<EthFlowRiskNodeRecord>;
}

