/**
 * UnBlock RESTful Web API
 * An blockchain analysis service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StackTraceElement } from './stack-trace-element';
import { Throwable } from './throwable';


export interface RestApiException { 
    apiErrorCode?: RestApiException.ApiErrorCodeEnum;
    cause?: Throwable;
    localizedMessage?: string;
    message?: string;
    stackTrace?: Array<StackTraceElement>;
    suppressed?: Array<Throwable>;
}
export namespace RestApiException {
    export type ApiErrorCodeEnum = 'ACCOUNT_NOT_FOUND' | 'UPDATE_PASSWORD_FALURE' | 'ROLE_NOT_FOUND' | 'ACCOUNT_DISABLED' | 'ACCOUNT_LOCKED' | 'BAD_CREDENTIAL' | 'INVALID_REFRESH_TOKEN' | 'INVALID_AUTHORIZATION_CODE' | 'ACCOUNT_EXISTED' | 'DUPLICATED_USER_REGISTRATION' | 'ADDRESS_NOT_FOUND' | 'BLOCK_NOT_FOUND' | 'TX_NOT_FOUND' | 'VOUT_NOT_FOUND' | 'INVALID_SCRIPT' | 'INVALID_GOOGLE_INFO' | 'ACCOUNT_ROLE_NOT_FOUND' | 'ROLE_NAME_DUPLICATED' | 'MOBILE_NOT_PROVIDED' | 'DUPLICATED_MOBILE' | 'MOBILE_ALREADY_VERIFIED' | 'INVALID_VERIFICATION_CODE' | 'BTC_FLOW_JOB_NOT_FOUND' | 'UPSTREAM_JOB_NOT_DONE' | 'INCONSISTENT_LEVEL' | 'INCONSISTENT_ADDRESS' | 'BTC_FLOW_ADDRESS_TAG_JOB_NOT_FOUND' | 'BTC_FLOW_RISK_JOB_NOT_FOUND' | 'BTC_FLOW_TX_JOB_NOT_FOUND' | 'JOB_TIMEOUT' | 'BTC_ADDRESS_SCAN_PIPELINE_NOT_FOUND' | 'SEARCH_NOT_FOUND';
    export const ApiErrorCodeEnum = {
        ACCOUNTNOTFOUND: 'ACCOUNT_NOT_FOUND' as ApiErrorCodeEnum,
        UPDATEPASSWORDFALURE: 'UPDATE_PASSWORD_FALURE' as ApiErrorCodeEnum,
        ROLENOTFOUND: 'ROLE_NOT_FOUND' as ApiErrorCodeEnum,
        ACCOUNTDISABLED: 'ACCOUNT_DISABLED' as ApiErrorCodeEnum,
        ACCOUNTLOCKED: 'ACCOUNT_LOCKED' as ApiErrorCodeEnum,
        BADCREDENTIAL: 'BAD_CREDENTIAL' as ApiErrorCodeEnum,
        INVALIDREFRESHTOKEN: 'INVALID_REFRESH_TOKEN' as ApiErrorCodeEnum,
        INVALIDAUTHORIZATIONCODE: 'INVALID_AUTHORIZATION_CODE' as ApiErrorCodeEnum,
        ACCOUNTEXISTED: 'ACCOUNT_EXISTED' as ApiErrorCodeEnum,
        DUPLICATEDUSERREGISTRATION: 'DUPLICATED_USER_REGISTRATION' as ApiErrorCodeEnum,
        ADDRESSNOTFOUND: 'ADDRESS_NOT_FOUND' as ApiErrorCodeEnum,
        BLOCKNOTFOUND: 'BLOCK_NOT_FOUND' as ApiErrorCodeEnum,
        TXNOTFOUND: 'TX_NOT_FOUND' as ApiErrorCodeEnum,
        VOUTNOTFOUND: 'VOUT_NOT_FOUND' as ApiErrorCodeEnum,
        INVALIDSCRIPT: 'INVALID_SCRIPT' as ApiErrorCodeEnum,
        INVALIDGOOGLEINFO: 'INVALID_GOOGLE_INFO' as ApiErrorCodeEnum,
        ACCOUNTROLENOTFOUND: 'ACCOUNT_ROLE_NOT_FOUND' as ApiErrorCodeEnum,
        ROLENAMEDUPLICATED: 'ROLE_NAME_DUPLICATED' as ApiErrorCodeEnum,
        MOBILENOTPROVIDED: 'MOBILE_NOT_PROVIDED' as ApiErrorCodeEnum,
        DUPLICATEDMOBILE: 'DUPLICATED_MOBILE' as ApiErrorCodeEnum,
        MOBILEALREADYVERIFIED: 'MOBILE_ALREADY_VERIFIED' as ApiErrorCodeEnum,
        INVALIDVERIFICATIONCODE: 'INVALID_VERIFICATION_CODE' as ApiErrorCodeEnum,
        BTCFLOWJOBNOTFOUND: 'BTC_FLOW_JOB_NOT_FOUND' as ApiErrorCodeEnum,
        UPSTREAMJOBNOTDONE: 'UPSTREAM_JOB_NOT_DONE' as ApiErrorCodeEnum,
        INCONSISTENTLEVEL: 'INCONSISTENT_LEVEL' as ApiErrorCodeEnum,
        INCONSISTENTADDRESS: 'INCONSISTENT_ADDRESS' as ApiErrorCodeEnum,
        BTCFLOWADDRESSTAGJOBNOTFOUND: 'BTC_FLOW_ADDRESS_TAG_JOB_NOT_FOUND' as ApiErrorCodeEnum,
        BTCFLOWRISKJOBNOTFOUND: 'BTC_FLOW_RISK_JOB_NOT_FOUND' as ApiErrorCodeEnum,
        BTCFLOWTXJOBNOTFOUND: 'BTC_FLOW_TX_JOB_NOT_FOUND' as ApiErrorCodeEnum,
        JOBTIMEOUT: 'JOB_TIMEOUT' as ApiErrorCodeEnum,
        BTCADDRESSSCANPIPELINENOTFOUND: 'BTC_ADDRESS_SCAN_PIPELINE_NOT_FOUND' as ApiErrorCodeEnum,
        SEARCHNOTFOUND: 'SEARCH_NOT_FOUND' as ApiErrorCodeEnum
    };
}


