/**
 * UnBlock RESTful Web API
 * An blockchain analysis service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { XrpFlowRiskNode } from './xrp-flow-risk-node';


export interface XrpFlowRiskRecord { 
    direction?: string;
    path?: Array<XrpFlowRiskNode>;
    totalScore?: number;
    totalScoreEv?: number;
}

