/**
 * UnBlock RESTful Web API
 * An blockchain analysis service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { XrpFlowRiskGraphJob } from './xrp-flow-risk-graph-job';


export interface XrpFlowRiskNodeJob { 
    bqJob?: string;
    createdTime?: Date;
    creatorId?: number;
    destDataset?: string;
    destProjectId?: string;
    destTable?: string;
    flowRiskGraphJob?: XrpFlowRiskGraphJob;
    flowRiskGraphJobId?: number;
    id?: number;
    updatedTime?: Date;
    updaterId?: number;
}

