/**
 * UnBlock RESTful Web API
 * An blockchain analysis service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';
import { XrpFlowAddressTagJob } from './xrp-flow-address-tag-job';
import { XrpFlowJob } from './xrp-flow-job';
import { XrpFlowRiskJob } from './xrp-flow-risk-job';
import { XrpFlowAddressTaintJob } from './xrp-flow-address-taint-job';
import { XrpRiskSummaryJob } from './xrp-risk-summary-job';


export interface XrpAddressScanPipeline { 
    address?: string;
    avgScore?: number;
    avgScoreEv?: number;
    backwardFlowJob?: XrpFlowJob;
    backwardFlowJobId?: number;
    createdTime?: Date;
    creatorId?: number;
    endingTime?: Date;
    flowAddressTagJob?: XrpFlowAddressTagJob;
    flowAddressTagJobId?: number;
    flowAddressTaintJob?: XrpFlowAddressTaintJob;
    flowAddressTaintJobId?: number;
    flowRiskJob?: XrpFlowRiskJob;
    flowRiskJobId?: number;
    forwardFlowJob?: XrpFlowJob;
    forwardFlowJobId?: number;
    id?: number;
    isCached?: boolean;
    maxLevel?: number;
    riskSummaryJob?: XrpRiskSummaryJob;
    riskSummaryJobId?: number;
    startingTime?: Date;
    status?: XrpAddressScanPipeline.StatusEnum;
    timeoutSecs?: number;
    totalScore?: number;
    totalScoreEv?: number;
    updatedTime?: Date;
    updater?: Account;
}
export namespace XrpAddressScanPipeline {
    export type StatusEnum = 'PENDING' | 'RUNNING' | 'COMPLETED' | 'FAILED';
    export const StatusEnum = {
        PENDING: 'PENDING' as StatusEnum,
        RUNNING: 'RUNNING' as StatusEnum,
        COMPLETED: 'COMPLETED' as StatusEnum,
        FAILED: 'FAILED' as StatusEnum
    };
}


