/**
 * UnBlock RESTful Web API
 * An blockchain analysis service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { XrpFlowRiskNodeJob } from './xrp-flow-risk-node-job';
import { XrpFlowRiskGraphJob } from './xrp-flow-risk-graph-job';
import { XrpFlowRiskEdgeJob } from './xrp-flow-risk-edge-job';
import { XrpFlowRiskEdgeRecord } from './xrp-flow-risk-edge-record';
import { XrpFlowRiskNodeRecord } from './xrp-flow-risk-node-record';


export interface XrpFlowRiskGraph { 
    edges?: Array<XrpFlowRiskEdgeRecord>;
    flowRiskEdgeJob?: XrpFlowRiskEdgeJob;
    flowRiskGraphJob?: XrpFlowRiskGraphJob;
    flowRiskNodeJob?: XrpFlowRiskNodeJob;
    nodes?: Array<XrpFlowRiskNodeRecord>;
}

