/**
 * UnBlock RESTful Web API
 * An blockchain analysis service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { XrpFlowRiskJob } from './xrp-flow-risk-job';


export interface XrpFlowRiskGraphJob { 
    address?: string;
    bqJob?: string;
    createdTime?: Date;
    creatorId?: number;
    destDataset?: string;
    destProjectId?: string;
    destTable?: string;
    endingTime?: Date;
    flowRiskJob?: XrpFlowRiskJob;
    flowRiskJobId?: number;
    id?: number;
    startingTime?: Date;
    tag?: string;
    updatedTime?: Date;
    updaterId?: number;
}

