/**
 * UnBlock RESTful Web API
 * An blockchain analysis service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

import { BtcFlowAddressTagJob } from '../model/btc-flow-address-tag-job';
import { BtcFlowAddressTagJobResultPage } from '../model/btc-flow-address-tag-job-result-page';
import { BtcFlowAddressTagJobStatus } from '../model/btc-flow-address-tag-job-status';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class BtcFlowAddressTagJobApiService {

    protected basePath = 'http://localhost:43125';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {

        if (configuration) {
            this.configuration = configuration;
            this.configuration.basePath = configuration.basePath || basePath || this.basePath;

        } else {
            this.configuration.basePath = basePath || this.basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }



    /**
     * createFlowAddressTagJob
     * @param body body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createFlowAddressTagJobUsingPOSTDefault(body: BtcFlowAddressTagJob, observe?: 'body', reportProgress?: boolean): Observable<BtcFlowAddressTagJob>;
    public createFlowAddressTagJobUsingPOSTDefault(body: BtcFlowAddressTagJob, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BtcFlowAddressTagJob>>;
    public createFlowAddressTagJobUsingPOSTDefault(body: BtcFlowAddressTagJob, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BtcFlowAddressTagJob>>;
    public createFlowAddressTagJobUsingPOSTDefault(body: BtcFlowAddressTagJob, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling createFlowAddressTagJobUsingPOSTDefault.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<BtcFlowAddressTagJob>(`${this.configuration.basePath}/api/btc-flow-address-tag-job`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getFlowAddressTagJobResult
     * @param id id
     * @param page page
     * @param size size
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFlowAddressTagJobResultUsingGETDefault(id: number, page: number, size: number, observe?: 'body', reportProgress?: boolean): Observable<BtcFlowAddressTagJobResultPage>;
    public getFlowAddressTagJobResultUsingGETDefault(id: number, page: number, size: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BtcFlowAddressTagJobResultPage>>;
    public getFlowAddressTagJobResultUsingGETDefault(id: number, page: number, size: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BtcFlowAddressTagJobResultPage>>;
    public getFlowAddressTagJobResultUsingGETDefault(id: number, page: number, size: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getFlowAddressTagJobResultUsingGETDefault.');
        }
        if (page === null || page === undefined) {
            throw new Error('Required parameter page was null or undefined when calling getFlowAddressTagJobResultUsingGETDefault.');
        }
        if (size === null || size === undefined) {
            throw new Error('Required parameter size was null or undefined when calling getFlowAddressTagJobResultUsingGETDefault.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('page', <any>page);
        }
        if (size !== undefined && size !== null) {
            queryParameters = queryParameters.set('size', <any>size);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<BtcFlowAddressTagJobResultPage>(`${this.configuration.basePath}/api/btc-flow-address-tag-job/${encodeURIComponent(String(id))}/result`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getFlowAddressTagJobStatus
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFlowAddressTagJobStatusUsingGETDefault(id: number, observe?: 'body', reportProgress?: boolean): Observable<BtcFlowAddressTagJobStatus>;
    public getFlowAddressTagJobStatusUsingGETDefault(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BtcFlowAddressTagJobStatus>>;
    public getFlowAddressTagJobStatusUsingGETDefault(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BtcFlowAddressTagJobStatus>>;
    public getFlowAddressTagJobStatusUsingGETDefault(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getFlowAddressTagJobStatusUsingGETDefault.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<BtcFlowAddressTagJobStatus>(`${this.configuration.basePath}/api/btc-flow-address-tag-job/${encodeURIComponent(String(id))}/status`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * nextFlowAddressTagJobResult
     * @param id id
     * @param token token
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public nextFlowAddressTagJobResultUsingGETDefault(id: number, token?: string, observe?: 'body', reportProgress?: boolean): Observable<BtcFlowAddressTagJobResultPage>;
    public nextFlowAddressTagJobResultUsingGETDefault(id: number, token?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BtcFlowAddressTagJobResultPage>>;
    public nextFlowAddressTagJobResultUsingGETDefault(id: number, token?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BtcFlowAddressTagJobResultPage>>;
    public nextFlowAddressTagJobResultUsingGETDefault(id: number, token?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling nextFlowAddressTagJobResultUsingGETDefault.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (token !== undefined && token !== null) {
            queryParameters = queryParameters.set('token', <any>token);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<BtcFlowAddressTagJobResultPage>(`${this.configuration.basePath}/api/btc-flow-address-tag-job/${encodeURIComponent(String(id))}/next-page`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
