/**
 * UnBlock RESTful Web API
 * An blockchain analysis service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

import { BtcRiskSummaryJob } from '../model/btc-risk-summary-job';
import { BtcRiskSummaryJobResult } from '../model/btc-risk-summary-job-result';
import { BtcRiskSummaryJobStatus } from '../model/btc-risk-summary-job-status';
import { BtcSingleAddressRoot } from '../model/btc-single-address-root';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class BtcRiskSummaryJobApiService {

    protected basePath = 'http://localhost:45531';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {

        if (configuration) {
            this.configuration = configuration;
            this.configuration.basePath = configuration.basePath || basePath || this.basePath;

        } else {
            this.configuration.basePath = basePath || this.basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }



    /**
     * createRiskSummaryJob
     * @param body body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createRiskSummaryJobUsingPOSTDefault(body: BtcRiskSummaryJob, observe?: 'body', reportProgress?: boolean): Observable<BtcRiskSummaryJob>;
    public createRiskSummaryJobUsingPOSTDefault(body: BtcRiskSummaryJob, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BtcRiskSummaryJob>>;
    public createRiskSummaryJobUsingPOSTDefault(body: BtcRiskSummaryJob, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BtcRiskSummaryJob>>;
    public createRiskSummaryJobUsingPOSTDefault(body: BtcRiskSummaryJob, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling createRiskSummaryJobUsingPOSTDefault.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<BtcRiskSummaryJob>(`${this.configuration.basePath}/api/btc-risk-summary-job`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getRiskSummaryJobResult
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getRiskSummaryJobResultUsingGETDefault(id: number, observe?: 'body', reportProgress?: boolean): Observable<BtcRiskSummaryJobResult>;
    public getRiskSummaryJobResultUsingGETDefault(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BtcRiskSummaryJobResult>>;
    public getRiskSummaryJobResultUsingGETDefault(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BtcRiskSummaryJobResult>>;
    public getRiskSummaryJobResultUsingGETDefault(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getRiskSummaryJobResultUsingGETDefault.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<BtcRiskSummaryJobResult>(`${this.configuration.basePath}/api/btc-risk-summary-job/${encodeURIComponent(String(id))}/result`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getRiskSummaryJobStatus
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getRiskSummaryJobStatusUsingGETDefault(id: number, observe?: 'body', reportProgress?: boolean): Observable<BtcRiskSummaryJobStatus>;
    public getRiskSummaryJobStatusUsingGETDefault(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BtcRiskSummaryJobStatus>>;
    public getRiskSummaryJobStatusUsingGETDefault(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BtcRiskSummaryJobStatus>>;
    public getRiskSummaryJobStatusUsingGETDefault(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getRiskSummaryJobStatusUsingGETDefault.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<BtcRiskSummaryJobStatus>(`${this.configuration.basePath}/api/btc-risk-summary-job/${encodeURIComponent(String(id))}/status`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * runRiskSummaryJob
     * @param body body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public runRiskSummaryJobUsingPOSTDefault(body: BtcSingleAddressRoot, observe?: 'body', reportProgress?: boolean): Observable<BtcRiskSummaryJobResult>;
    public runRiskSummaryJobUsingPOSTDefault(body: BtcSingleAddressRoot, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BtcRiskSummaryJobResult>>;
    public runRiskSummaryJobUsingPOSTDefault(body: BtcSingleAddressRoot, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BtcRiskSummaryJobResult>>;
    public runRiskSummaryJobUsingPOSTDefault(body: BtcSingleAddressRoot, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling runRiskSummaryJobUsingPOSTDefault.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<BtcRiskSummaryJobResult>(`${this.configuration.basePath}/api/btc-risk-summary-job/run`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
