/**
 * UnBlock RESTful Web API
 * An blockchain analysis service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

import { EthFlowRiskJob } from '../model/eth-flow-risk-job';
import { EthFlowRiskJobResultPage } from '../model/eth-flow-risk-job-result-page';
import { EthFlowRiskJobStatus } from '../model/eth-flow-risk-job-status';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class EthFlowRiskJobApiService {

    protected basePath = 'http://localhost:45531';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {

        if (configuration) {
            this.configuration = configuration;
            this.configuration.basePath = configuration.basePath || basePath || this.basePath;

        } else {
            this.configuration.basePath = basePath || this.basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }



    /**
     * createFlowRiskJob
     * @param body body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createFlowRiskJobUsingPOSTDefault1(body: EthFlowRiskJob, observe?: 'body', reportProgress?: boolean): Observable<EthFlowRiskJob>;
    public createFlowRiskJobUsingPOSTDefault1(body: EthFlowRiskJob, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EthFlowRiskJob>>;
    public createFlowRiskJobUsingPOSTDefault1(body: EthFlowRiskJob, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EthFlowRiskJob>>;
    public createFlowRiskJobUsingPOSTDefault1(body: EthFlowRiskJob, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling createFlowRiskJobUsingPOSTDefault1.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<EthFlowRiskJob>(`${this.configuration.basePath}/api/eth-flow-risk-job`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getFlowRiskJobResult
     * @param id id
     * @param page page
     * @param size size
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFlowRiskJobResultUsingGETDefault1(id: number, page: number, size: number, observe?: 'body', reportProgress?: boolean): Observable<EthFlowRiskJobResultPage>;
    public getFlowRiskJobResultUsingGETDefault1(id: number, page: number, size: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EthFlowRiskJobResultPage>>;
    public getFlowRiskJobResultUsingGETDefault1(id: number, page: number, size: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EthFlowRiskJobResultPage>>;
    public getFlowRiskJobResultUsingGETDefault1(id: number, page: number, size: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getFlowRiskJobResultUsingGETDefault1.');
        }
        if (page === null || page === undefined) {
            throw new Error('Required parameter page was null or undefined when calling getFlowRiskJobResultUsingGETDefault1.');
        }
        if (size === null || size === undefined) {
            throw new Error('Required parameter size was null or undefined when calling getFlowRiskJobResultUsingGETDefault1.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('page', <any>page);
        }
        if (size !== undefined && size !== null) {
            queryParameters = queryParameters.set('size', <any>size);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<EthFlowRiskJobResultPage>(`${this.configuration.basePath}/api/eth-flow-risk-job/${encodeURIComponent(String(id))}/result`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getFlowRiskJobStatus
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFlowRiskJobStatusUsingGETDefault1(id: number, observe?: 'body', reportProgress?: boolean): Observable<EthFlowRiskJobStatus>;
    public getFlowRiskJobStatusUsingGETDefault1(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EthFlowRiskJobStatus>>;
    public getFlowRiskJobStatusUsingGETDefault1(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EthFlowRiskJobStatus>>;
    public getFlowRiskJobStatusUsingGETDefault1(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getFlowRiskJobStatusUsingGETDefault1.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<EthFlowRiskJobStatus>(`${this.configuration.basePath}/api/eth-flow-risk-job/${encodeURIComponent(String(id))}/status`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * nextFlowRiskJobResult
     * @param id id
     * @param token token
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public nextFlowRiskJobResultUsingGETDefault1(id: number, token?: string, observe?: 'body', reportProgress?: boolean): Observable<EthFlowRiskJobResultPage>;
    public nextFlowRiskJobResultUsingGETDefault1(id: number, token?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EthFlowRiskJobResultPage>>;
    public nextFlowRiskJobResultUsingGETDefault1(id: number, token?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EthFlowRiskJobResultPage>>;
    public nextFlowRiskJobResultUsingGETDefault1(id: number, token?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling nextFlowRiskJobResultUsingGETDefault1.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (token !== undefined && token !== null) {
            queryParameters = queryParameters.set('token', <any>token);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<EthFlowRiskJobResultPage>(`${this.configuration.basePath}/api/eth-flow-risk-job/${encodeURIComponent(String(id))}/next-page`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
