/**
 * UnBlock RESTful Web API
 * An blockchain analysis service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

import { PageOfXrpAddressScanPipeline } from '../model/page-of-xrp-address-scan-pipeline';
import { XrpAddressScanPipeline } from '../model/xrp-address-scan-pipeline';
import { XrpSingleAddressRoot } from '../model/xrp-single-address-root';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class XrpAddressScanPipelineApiService {

    protected basePath = 'http://localhost:43125';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {

        if (configuration) {
            this.configuration = configuration;
            this.configuration.basePath = configuration.basePath || basePath || this.basePath;

        } else {
            this.configuration.basePath = basePath || this.basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }



    /**
     * createBteAddressScanPipeline
     * @param body body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createBteAddressScanPipelineUsingPOSTDefault2(body: XrpSingleAddressRoot, observe?: 'body', reportProgress?: boolean): Observable<XrpAddressScanPipeline>;
    public createBteAddressScanPipelineUsingPOSTDefault2(body: XrpSingleAddressRoot, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<XrpAddressScanPipeline>>;
    public createBteAddressScanPipelineUsingPOSTDefault2(body: XrpSingleAddressRoot, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<XrpAddressScanPipeline>>;
    public createBteAddressScanPipelineUsingPOSTDefault2(body: XrpSingleAddressRoot, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling createBteAddressScanPipelineUsingPOSTDefault2.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<XrpAddressScanPipeline>(`${this.configuration.basePath}/api/xrp-address-scan-pipeline`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getXrpAddressScanPipeline
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getXrpAddressScanPipelineUsingGETDefault(id: number, observe?: 'body', reportProgress?: boolean): Observable<XrpAddressScanPipeline>;
    public getXrpAddressScanPipelineUsingGETDefault(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<XrpAddressScanPipeline>>;
    public getXrpAddressScanPipelineUsingGETDefault(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<XrpAddressScanPipeline>>;
    public getXrpAddressScanPipelineUsingGETDefault(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getXrpAddressScanPipelineUsingGETDefault.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<XrpAddressScanPipeline>(`${this.configuration.basePath}/api/xrp-address-scan-pipeline/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * paginateXrpAddressScanPipelines
     * @param page page
     * @param size size
     * @param creatorId creatorId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public paginateXrpAddressScanPipelinesUsingGETDefault(page?: number, size?: number, creatorId?: number, observe?: 'body', reportProgress?: boolean): Observable<PageOfXrpAddressScanPipeline>;
    public paginateXrpAddressScanPipelinesUsingGETDefault(page?: number, size?: number, creatorId?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PageOfXrpAddressScanPipeline>>;
    public paginateXrpAddressScanPipelinesUsingGETDefault(page?: number, size?: number, creatorId?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PageOfXrpAddressScanPipeline>>;
    public paginateXrpAddressScanPipelinesUsingGETDefault(page?: number, size?: number, creatorId?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('page', <any>page);
        }
        if (size !== undefined && size !== null) {
            queryParameters = queryParameters.set('size', <any>size);
        }
        if (creatorId !== undefined && creatorId !== null) {
            queryParameters = queryParameters.set('creatorId', <any>creatorId);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<PageOfXrpAddressScanPipeline>(`${this.configuration.basePath}/api/xrp-address-scan-pipeline`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
